import { connectDB } from "./config/db";
import { Product } from "./models/product.model";

// Ürün verisini sadece 'data' arrayi olarak alıyoruz
const response = {
  message: "Ürünler başarıyla getirildi",
  status: "success",
  currentPage: 1,
  totalPages: 5,
  totalItems: 100,
  data: [
    {
      name: "Akıllı Telefon",
      price: 1620.79,
      productCode: "P001",
      barcode: "6339915154820",
      stock: 83,
      status: false,
      category: "Elektronik",
      description: "Kolay taşınabilir ve hafif.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Laptop",
      price: 275.06,
      productCode: "P002",
      barcode: "8730690284032",
      stock: 64,
      status: false,
      category: "Elektronik",
      description: "Ergonomik tasarımıyla dikkat çeker.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Bluetooth Kulaklık",
      price: 1393.68,
      productCode: "P003",
      barcode: "3096743544874",
      stock: 4,
      status: false,
      category: "Elektronik",
      description: "Uzun ömürlü kullanım sağlar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Tablet",
      price: 2006.61,
      productCode: "P004",
      barcode: "2807099787970",
      stock: 19,
      status: true,
      category: "Elektronik",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Smart TV",
      price: 510.44,
      productCode: "P005",
      barcode: "3001829430674",
      stock: 85,
      status: true,
      category: "Elektronik",
      description: "Günlük kullanım için idealdir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Powerbank",
      price: 3896.92,
      productCode: "P006",
      barcode: "2529409390061",
      stock: 79,
      status: true,
      category: "Elektronik",
      description: "Günlük kullanım için idealdir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Kablosuz Mouse",
      price: 1173.78,
      productCode: "P007",
      barcode: "2376039431118",
      stock: 26,
      status: false,
      category: "Elektronik",
      description: "Enerji tasarrufludur.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Klavye",
      price: 3440.67,
      productCode: "P008",
      barcode: "1156705043472",
      stock: 50,
      status: false,
      category: "Elektronik",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Oyun Konsolu",
      price: 4655.17,
      productCode: "P009",
      barcode: "2167197219314",
      stock: 60,
      status: true,
      category: "Elektronik",
      description: "Kolay taşınabilir ve hafif.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Webcam",
      price: 3900.41,
      productCode: "P010",
      barcode: "4239757364772",
      stock: 100,
      status: true,
      category: "Elektronik",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Tişört",
      price: 3909.36,
      productCode: "P011",
      barcode: "6849191980028",
      stock: 19,
      status: true,
      category: "Giyim",
      description: "Ergonomik tasarımıyla dikkat çeker.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Kot Pantolon",
      price: 2129.96,
      productCode: "P012",
      barcode: "5108637184373",
      stock: 4,
      status: false,
      category: "Giyim",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Sneaker",
      price: 722.87,
      productCode: "P013",
      barcode: "4600105670038",
      stock: 6,
      status: false,
      category: "Giyim",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Ceket",
      price: 741.89,
      productCode: "P014",
      barcode: "2758542340409",
      stock: 35,
      status: false,
      category: "Giyim",
      description: "Uzun ömürlü kullanım sağlar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Etek",
      price: 1175.02,
      productCode: "P015",
      barcode: "4445954595477",
      stock: 40,
      status: true,
      category: "Giyim",
      description: "Günlük kullanım için idealdir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Elbise",
      price: 1556.02,
      productCode: "P016",
      barcode: "5980979441206",
      stock: 20,
      status: true,
      category: "Giyim",
      description: "Modern ve şık bir tasarıma sahiptir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Sweatshirt",
      price: 4850.81,
      productCode: "P017",
      barcode: "2162143558917",
      stock: 68,
      status: true,
      category: "Giyim",
      description: "Uzun ömürlü kullanım sağlar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Mont",
      price: 544.5,
      productCode: "P018",
      barcode: "7529815013369",
      stock: 90,
      status: true,
      category: "Giyim",
      description: "Kolay taşınabilir ve hafif.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Şapka",
      price: 262.88,
      productCode: "P019",
      barcode: "1740411254781",
      stock: 43,
      status: false,
      category: "Giyim",
      description: "Yumuşak dokusu ile rahat bir kullanım sunar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Güneş Gözlüğü",
      price: 4768.98,
      productCode: "P020",
      barcode: "4095210259004",
      stock: 9,
      status: true,
      category: "Giyim",
      description: "Enerji tasarrufludur.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Bileklik",
      price: 320.5,
      productCode: "P021",
      barcode: "9876543210987",
      stock: 75,
      status: true,
      category: "Elektronik",
      description: "Adım ve uyku takibi, bildirimler.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Kablosuz Şarj Ped",
      price: 450.0,
      productCode: "P022",
      barcode: "8765432109876",
      stock: 110,
      status: true,
      category: "Elektronik",
      description: "Hızlı ve pratik şarj imkanı.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Mini Projektör",
      price: 2800.0,
      productCode: "P023",
      barcode: "7654321098765",
      stock: 30,
      status: true,
      category: "Elektronik",
      description: "Taşınabilir sinema deneyimi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Akıllı Ev Kamerası",
      price: 950.0,
      productCode: "P024",
      barcode: "6543210987654",
      stock: 55,
      status: true,
      category: "Elektronik",
      description: "Uzaktan izleme ve hareket algılama.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Oyun Kolu",
      price: 650.0,
      productCode: "P025",
      barcode: "5432109876543",
      stock: 80,
      status: true,
      category: "Elektronik",
      description: "Titreşimli geri bildirim ve hassas kontrol.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Ses Kayıt Cihazı",
      price: 1800.0,
      productCode: "P026",
      barcode: "4321098765432",
      stock: 40,
      status: true,
      category: "Elektronik",
      description: "Yüksek kaliteli ses kaydı.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Aydınlatma Seti",
      price: 700.0,
      productCode: "P027",
      barcode: "3210987654321",
      stock: 60,
      status: true,
      category: "Elektronik",
      description: "Ortamı kişiselleştirin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Dizüstü Bilgisayar Standı",
      price: 1200.0,
      productCode: "P028",
      barcode: "2109876543210",
      stock: 90,
      status: true,
      category: "Elektronik",
      description: "Ergonomik çalışma alanı oluşturur.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Akıllı Ev Sensörü",
      price: 500.0,
      productCode: "P029",
      barcode: "1098765432109",
      stock: 130,
      status: true,
      category: "Elektronik",
      description: "Sıcaklık ve nem takibi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Fiş",
      price: 300.0,
      productCode: "P030",
      barcode: "0987654321098",
      stock: 180,
      status: true,
      category: "Elektronik",
      description: "Cihazlarınızı uzaktan kontrol edin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Hoodie",
      price: 600.0,
      productCode: "P031",
      barcode: "9876543210986",
      stock: 120,
      status: true,
      category: "Giyim",
      description: "Sıcak ve rahat, günlük kullanım için.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Eşofman Altı",
      price: 450.0,
      productCode: "P032",
      barcode: "8765432109875",
      stock: 90,
      status: true,
      category: "Giyim",
      description: "Spor ve rahat günler için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Kısa Kollu Gömlek",
      price: 300.0,
      productCode: "P033",
      barcode: "7654321098764",
      stock: 70,
      status: true,
      category: "Giyim",
      description: "Yazlık ve şık.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Şifon Bluz",
      price: 250.0,
      productCode: "P034",
      barcode: "6543210987653",
      stock: 85,
      status: true,
      category: "Giyim",
      description: "Hafif ve zarif.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Triko Kazak",
      price: 500.0,
      productCode: "P035",
      barcode: "5432109876542",
      stock: 50,
      status: true,
      category: "Giyim",
      description: "Soğuk havalar için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Kot Şort",
      price: 350.0,
      productCode: "P036",
      barcode: "4321098765431",
      stock: 130,
      status: true,
      category: "Giyim",
      description: "Yaz stilinin vazgeçilmezi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Yüzme Şortu",
      price: 280.0,
      productCode: "P037",
      barcode: "3210987654320",
      stock: 90,
      status: true,
      category: "Giyim",
      description: "Hızlı kuruyan kumaş, plaj ve havuz için.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Tek Parça Mayo",
      price: 550.0,
      productCode: "P038",
      barcode: "2109876543219",
      stock: 75,
      status: true,
      category: "Giyim",
      description: "Şık ve rahat tasarım.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Bambu Çorap Seti",
      price: 100.0,
      productCode: "P039",
      barcode: "1098765432108",
      stock: 300,
      status: true,
      category: "Giyim",
      description: "Yumuşak ve nefes alabilen.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Dikişsiz Spor Sütyeni",
      price: 280.0,
      productCode: "P040",
      barcode: "0987654321097",
      stock: 120,
      status: true,
      category: "Giyim",
      description: "Maksimum destek ve konfor.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Hoparlör",
      price: 1500.0,
      productCode: "P041",
      barcode: "9876543210985",
      stock: 60,
      status: true,
      category: "Elektronik",
      description: "Sesli asistan ve kaliteli ses.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Akıllı Anahtar",
      price: 700.0,
      productCode: "P042",
      barcode: "8765432109874",
      stock: 95,
      status: true,
      category: "Elektronik",
      description: "Anahtarlarınızı kaybetmeyin, uzaktan bulun.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Mekanik Klavye",
      price: 1100.0,
      productCode: "P043",
      barcode: "7654321098763",
      stock: 45,
      status: true,
      category: "Elektronik",
      description: "Oyun ve yazma için üstün performans.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Kablosuz Şarj İstasyonu",
      price: 850.0,
      productCode: "P044",
      barcode: "6543210987652",
      stock: 60,
      status: true,
      category: "Elektronik",
      description: "Birden fazla cihazı aynı anda şarj edin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Akıllı Buzdolabı",
      price: 9500.0,
      productCode: "P045",
      barcode: "5432109876541",
      stock: 10,
      status: true,
      category: "Elektronik",
      description: "Yemek takibi ve uzaktan kontrol.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Elektrikli Scooter",
      price: 7000.0,
      productCode: "P046",
      barcode: "4321098765430",
      stock: 25,
      status: true,
      category: "Elektronik",
      description: "Şehir içi ulaşımda pratik ve çevre dostu.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "VR Kask",
      price: 5500.0,
      productCode: "P047",
      barcode: "3210987654319",
      stock: 15,
      status: true,
      category: "Elektronik",
      description: "Sanal gerçeklik oyunları ve deneyimleri.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Akıllı Kapı Zili",
      price: 1200.0,
      productCode: "P048",
      barcode: "2109876543208",
      stock: 35,
      status: true,
      category: "Elektronik",
      description: "Güvenliği artırın, ziyaretçileri uzaktan görün.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Akıllı Klima",
      price: 4000.0,
      productCode: "P049",
      barcode: "1098765432097",
      stock: 20,
      status: true,
      category: "Elektronik",
      description: "Enerji verimli ve uzaktan kontrol edilebilir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Televizyon Kumandası",
      price: 400.0,
      productCode: "P050",
      barcode: "0987654320986",
      stock: 100,
      status: true,
      category: "Elektronik",
      description: "Tüm akıllı cihazlarınızı tek kumandadan yönetin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Kadın Jean Ceket",
      price: 750.0,
      productCode: "P051",
      barcode: "9876543210984",
      stock: 80,
      status: true,
      category: "Giyim",
      description: "Klasik ve şık, her mevsim giyilebilir.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Erkek Chino Pantolon",
      price: 600.0,
      productCode: "P052",
      barcode: "8765432109873",
      stock: 95,
      status: true,
      category: "Giyim",
      description: "Hem günlük hem de iş için uygun.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Deri Ayakkabı",
      price: 1800.0,
      productCode: "P053",
      barcode: "7654321098762",
      stock: 40,
      status: true,
      category: "Giyim",
      description: "Klasik ve dayanıklı, resmi günler için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Kışlık Şapka",
      price: 200.0,
      productCode: "P054",
      barcode: "6543210987651",
      stock: 150,
      status: true,
      category: "Giyim",
      description: "Soğuktan koruyan şık bere.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Fular",
      price: 150.0,
      productCode: "P055",
      barcode: "5432109876540",
      stock: 200,
      status: true,
      category: "Giyim",
      description: "Kombinlerinize renk katın.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Kot Elbise",
      price: 900.0,
      productCode: "P056",
      barcode: "4321098765429",
      stock: 60,
      status: true,
      category: "Giyim",
      description: "Günlük kullanım için rahat ve şık.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Yelek",
      price: 400.0,
      productCode: "P057",
      barcode: "3210987654318",
      stock: 110,
      status: true,
      category: "Giyim",
      description: "Katmanlı kombinler için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Yağmurluk",
      price: 850.0,
      productCode: "P058",
      barcode: "2109876543207",
      stock: 50,
      status: true,
      category: "Giyim",
      description: "Su geçirmez ve hafif.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Şık Eldiven",
      price: 180.0,
      productCode: "P059",
      barcode: "1098765432096",
      stock: 100,
      status: true,
      category: "Giyim",
      description: "Ellerinizi sıcak tutar ve şık bir görünüm sunar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Spor Çorapları",
      price: 90.0,
      productCode: "P060",
      barcode: "0987654320985",
      stock: 250,
      status: true,
      category: "Giyim",
      description: "Nefes alabilen ve teri emen kumaş.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Kablolu Kulaklık",
      price: 150.0,
      productCode: "P061",
      barcode: "9876543210983",
      stock: 200,
      status: true,
      category: "Elektronik",
      description: "Net ses ve konforlu kullanım.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Gaming Mouse Pad",
      price: 70.0,
      productCode: "P062",
      barcode: "8765432109872",
      stock: 180,
      status: true,
      category: "Elektronik",
      description: "Hassas takip için optimize edilmiş yüzey.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Kapı Kilidi",
      price: 2500.0,
      productCode: "P063",
      barcode: "7654321098761",
      stock: 20,
      status: true,
      category: "Elektronik",
      description: "Uzaktan kontrol ve anahtarsız giriş.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Akıllı Sulama Sistemi",
      price: 900.0,
      productCode: "P064",
      barcode: "6543210987650",
      stock: 30,
      status: true,
      category: "Elektronik",
      description: "Bitkilerinizi otomatik sulayın.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "E-Kitap Okuyucu",
      price: 1000.0,
      productCode: "P065",
      barcode: "5432109876539",
      stock: 50,
      status: true,
      category: "Elektronik",
      description: "Göz yormayan ekran, binlerce kitap kapasitesi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Akıllı Bileklik Şarj Aleti",
      price: 200.0,
      productCode: "P066",
      barcode: "4321098765428",
      stock: 150,
      status: true,
      category: "Elektronik",
      description: "Hızlı ve güvenli şarj.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Powerbank 20000mAh",
      price: 1500.0,
      productCode: "P067",
      barcode: "3210987654317",
      stock: 70,
      status: true,
      category: "Elektronik",
      description: "Uzun süreli kullanım için yüksek kapasite.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Kablolu Kulak İçi Kulaklık",
      price: 80.0,
      productCode: "P068",
      barcode: "2109876543206",
      stock: 220,
      status: true,
      category: "Elektronik",
      description: "Gürültü izolasyonu ve kaliteli ses.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Bluetooth Verici",
      price: 400.0,
      productCode: "P069",
      barcode: "1098765432095",
      stock: 90,
      status: true,
      category: "Elektronik",
      description: "Bluetooth olmayan cihazlara kablosuz bağlantı.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Dizüstü Bilgisayar Çantası",
      price: 600.0,
      productCode: "P070",
      barcode: "0987654320984",
      stock: 110,
      status: true,
      category: "Elektronik",
      description: "Laptopunuzu güvenle taşıyın.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Kısa Tulum",
      price: 550.0,
      productCode: "P071",
      barcode: "9876543210982",
      stock: 70,
      status: true,
      category: "Giyim",
      description: "Yaz aylarında şık ve rahat bir seçenek.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Erkek Sandalet",
      price: 400.0,
      productCode: "P072",
      barcode: "8765432109871",
      stock: 90,
      status: true,
      category: "Giyim",
      description: "Yazlık ve konforlu.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Kadın Sandalet",
      price: 350.0,
      productCode: "P073",
      barcode: "7654321098760",
      stock: 100,
      status: true,
      category: "Giyim",
      description: "Yazlık ve şık.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Spor Taytı Erkek",
      price: 480.0,
      productCode: "P074",
      barcode: "6543210987649",
      stock: 120,
      status: true,
      category: "Giyim",
      description: "Antrenmanlar için esnek ve rahat.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Kısa Kollu Crop Top",
      price: 180.0,
      productCode: "P075",
      barcode: "5432109876538",
      stock: 150,
      status: true,
      category: "Giyim",
      description: "Modern ve şık, yazlık kombinler için.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Uzun Çorap Seti",
      price: 120.0,
      productCode: "P076",
      barcode: "4321098765427",
      stock: 200,
      status: true,
      category: "Giyim",
      description: "Botlarla giymek için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Atkı",
      price: 220.0,
      productCode: "P077",
      barcode: "3210987654316",
      stock: 80,
      status: true,
      category: "Giyim",
      description: "Kışın sıcak tutan şık aksesuar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Basic Tişört Seti",
      price: 300.0,
      productCode: "P078",
      barcode: "2109876543205",
      stock: 180,
      status: true,
      category: "Giyim",
      description: "Gardırobunuzun temel parçaları.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Uzun Kollu Elbise",
      price: 1200.0,
      productCode: "P079",
      barcode: "1098765432094",
      stock: 60,
      status: true,
      category: "Giyim",
      description: "Sonbahar ve kış için şık ve rahat.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Desenli Etek",
      price: 700.0,
      productCode: "P080",
      barcode: "0987654320983",
      stock: 90,
      status: true,
      category: "Giyim",
      description: "Canlı desenlerle stilinizi tamamlayın.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Kahve Makinesi",
      price: 3500.0,
      productCode: "P081",
      barcode: "9876543210981",
      stock: 18,
      status: true,
      category: "Elektronik",
      description: "Telefonunuzdan kahve hazırlayın.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Robot Süpürge ve Mop",
      price: 6000.0,
      productCode: "P082",
      barcode: "8765432109870",
      stock: 12,
      status: true,
      category: "Elektronik",
      description: "Evinizi hem süpürür hem de siler.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Ev Güvenlik Seti",
      price: 4200.0,
      productCode: "P083",
      barcode: "7654321098759",
      stock: 25,
      status: true,
      category: "Elektronik",
      description: "Kamera, sensörler ve alarm sistemi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "Taşınabilir Mini Hoparlör",
      price: 280.0,
      productCode: "P084",
      barcode: "6543210987648",
      stock: 150,
      status: true,
      category: "Elektronik",
      description: "Küçük boyut, güçlü ses.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Akıllı Tartı ve Vücut Analizi",
      price: 950.0,
      productCode: "P085",
      barcode: "5432109876537",
      stock: 60,
      status: true,
      category: "Elektronik",
      description: "Kilo, yağ oranı, kas kütlesi takibi.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Dijital Fotoğraf Çerçevesi",
      price: 1100.0,
      productCode: "P086",
      barcode: "4321098765426",
      stock: 40,
      status: true,
      category: "Elektronik",
      description: "Anılarınızı dijital ortamda sergileyin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Ev Sensör Kiti",
      price: 1800.0,
      productCode: "P087",
      barcode: "3210987654315",
      stock: 30,
      status: true,
      category: "Elektronik",
      description: "Kapı/pencere, hareket ve su sızıntı sensörleri.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Bluetooth Klavye",
      price: 700.0,
      productCode: "P088",
      barcode: "2109876543204",
      stock: 90,
      status: true,
      category: "Elektronik",
      description: "Tablet ve telefonlarla uyumlu.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-1.png",
    },
    {
      name: "USB C Hub",
      price: 350.0,
      productCode: "P089",
      barcode: "1098765432093",
      stock: 120,
      status: true,
      category: "Elektronik",
      description: "Birden fazla bağlantı noktası sağlar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
    {
      name: "Akıllı Ev Hava Kalitesi Monitörü",
      price: 1400.0,
      productCode: "P090",
      barcode: "0987654320982",
      stock: 45,
      status: true,
      category: "Elektronik",
      description: "İç mekan hava kalitesini takip edin.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Erkek Gömlek",
      price: 500.0,
      productCode: "P091",
      barcode: "9876543210980",
      stock: 110,
      status: true,
      category: "Giyim",
      description: "İş veya günlük kullanım için klasik kesim.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Kadın Pantolon",
      price: 750.0,
      productCode: "P092",
      barcode: "8765432109869",
      stock: 80,
      status: true,
      category: "Giyim",
      description: "Rahat ve şık, iş veya günlük kullanım.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Spor Ayakkabı Beyaz",
      price: 1000.0,
      productCode: "P093",
      barcode: "7654321098758",
      stock: 95,
      status: true,
      category: "Giyim",
      description: "Her kombine uyum sağlayan klasik beyaz spor ayakkabı.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Yün Atkı",
      price: 300.0,
      productCode: "P094",
      barcode: "6543210987647",
      stock: 140,
      status: true,
      category: "Giyim",
      description: "Kış aylarında sıcak ve konforlu.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Erkek Tişört Seti",
      price: 400.0,
      productCode: "P095",
      barcode: "5432109876536",
      stock: 180,
      status: true,
      category: "Giyim",
      description: "Günlük kullanım için farklı renklerde basic tişörtler.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Kadın Bluz Çeşitleri",
      price: 380.0,
      productCode: "P096",
      barcode: "4321098765425",
      stock: 100,
      status: true,
      category: "Giyim",
      description: "Farklı yaka ve desenlerde şık bluzlar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-4.png",
    },
    {
      name: "Örgü Kazak",
      price: 650.0,
      productCode: "P097",
      barcode: "3210987654314",
      stock: 70,
      status: true,
      category: "Giyim",
      description: "El örgüsü hissi veren sıcak ve modern kazak.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Kadın Trençkot",
      price: 1500.0,
      productCode: "P098",
      barcode: "2109876543203",
      stock: 40,
      status: true,
      category: "Giyim",
      description: "Klasik ve şık, her mevsim için ideal.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-3.png",
    },
    {
      name: "Yazlık Şapka Seti",
      price: 250.0,
      productCode: "P099",
      barcode: "1098765432092",
      stock: 160,
      status: true,
      category: "Giyim",
      description: "Farklı renk ve modellerde yazlık şapkalar.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-2.png",
    },
    {
      name: "Renkli Güneş Gözlüğü",
      price: 550.0,
      productCode: "P100",
      barcode: "0987654320981",
      stock: 55,
      status: true,
      category: "Giyim",
      description: "Canlı renklerde çerçeveler ve UV koruması.",
      imageUrl: "https://isiksoft-app-space.fra1.digitaloceanspaces.com/devcase/product-5.png",
    },
  ],
};

async function seed() {
  try {
    await connectDB();

    // Var olan ürünleri temizle (isteğe bağlı)
    await Product.deleteMany({});
    console.log("🗑️ Var olan ürünler silindi");

    // Ürünleri ekle
    await Product.insertMany(response.data);
    console.log("✅ Ürünler başarıyla eklendi");

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed sırasında hata:", error);
    process.exit(1);
  }
}

seed();
